### ISSUE TITLE
System.InvalidOperationException in SevenZipSharp.dll

### ISSUE THREAD

**Issue by sepehr1014** [phillipp/SevenZipSharp#2]
Hello dear @phillipp and thanks for this great project.
Trying the WPF sample, after extracting a file, an exception is thrown:
`System.InvalidOperationException was unhandled by user code
  HResult=-2146233079
  Message=SevenZipExtractor instance must not be disposed while making an asynchronous method call.
  Source=SevenZipSharp
  StackTrace:
       at SevenZip.SevenZipExtractor.Dispose() in c:\Users\Sepehr\Desktop\SevenZipSharp-master\SevenZip\SevenZipExtractor.cs:line 807
       at SevenZipTestWPF.MainWindow.extr_ExtractionFinished(Object sender, EventArgs e) in c:\Users\Sepehr\Desktop\SevenZipSharp-master\SevenZipTestWPF\MainWindow.xaml.cs:line 78
       at SevenZip.SevenZipBase.<OnEvent>b__0[T](EventHandler1 h, T ee) in c:\Users\Sepehr\Desktop\SevenZipSharp-master\SevenZip\Common.cs:line 141`

**Comment by sepehr1014** [comment]
We can remove the call to `Dispose` method after completion, but isn't it necessary?
